/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectFiles;

/**
 *
 * @author sajid
 */
public class Accountant extends javax.swing.JFrame {

    /**
     * Creates new form Accountant
     */
    public Accountant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccountantBackground = new javax.swing.JPanel();
        DailySales = new javax.swing.JLabel();
        Invoices = new javax.swing.JLabel();
        Salary = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accountant");

        AccountantBackground.setBackground(new java.awt.Color(204, 255, 255));
        AccountantBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccountantBackgroundMouseExited(evt);
            }
        });

        DailySales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DailySales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before daily sales.png"))); // NOI18N
        DailySales.setText("Daily Sales");
        DailySales.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                DailySalesMouseMoved(evt);
            }
        });
        DailySales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DailySalesMouseExited(evt);
            }
        });

        Invoices.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Invoices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before expenses.png"))); // NOI18N
        Invoices.setText("Expenses");
        Invoices.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                InvoicesMouseMoved(evt);
            }
        });
        Invoices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InvoicesMouseExited(evt);
            }
        });

        Salary.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Salary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before invoice.png"))); // NOI18N
        Salary.setText("Invoices");
        Salary.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SalaryMouseMoved(evt);
            }
        });
        Salary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalaryMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/pharma-A(logo).png"))); // NOI18N
        jLabel1.setText("       Welcome to PharmaA Accounts Module");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please choose your Option");

        javax.swing.GroupLayout AccountantBackgroundLayout = new javax.swing.GroupLayout(AccountantBackground);
        AccountantBackground.setLayout(AccountantBackgroundLayout);
        AccountantBackgroundLayout.setHorizontalGroup(
            AccountantBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountantBackgroundLayout.createSequentialGroup()
                .addGroup(AccountantBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccountantBackgroundLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(AccountantBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AccountantBackgroundLayout.createSequentialGroup()
                                .addComponent(DailySales, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(Invoices, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AccountantBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        AccountantBackgroundLayout.setVerticalGroup(
            AccountantBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountantBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(AccountantBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DailySales, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Invoices, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountantBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccountantBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DailySalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DailySalesMouseExited
DailySales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before daily sales.png"))); // NOI18N
    }//GEN-LAST:event_DailySalesMouseExited

    private void DailySalesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DailySalesMouseMoved
DailySales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/after daily sales.png"))); // NOI18N
    }//GEN-LAST:event_DailySalesMouseMoved

    private void AccountantBackgroundMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountantBackgroundMouseExited

    }//GEN-LAST:event_AccountantBackgroundMouseExited

    private void InvoicesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoicesMouseExited
Invoices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before expenses.png"))); // NOI18N
    }//GEN-LAST:event_InvoicesMouseExited

    private void InvoicesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoicesMouseMoved
Invoices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/after expenses.png"))); // NOI18N
    }//GEN-LAST:event_InvoicesMouseMoved

    private void SalaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalaryMouseExited
Salary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before invoice.png"))); // NOI18N
    }//GEN-LAST:event_SalaryMouseExited

    private void SalaryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalaryMouseMoved
Salary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/after invoice.png"))); // NOI18N
    }//GEN-LAST:event_SalaryMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accountant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountantBackground;
    private javax.swing.JLabel DailySales;
    private javax.swing.JLabel Invoices;
    private javax.swing.JLabel Salary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
