/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectFiles;

/**
 *
 * @author sajid
 */
public class AdminScreen extends javax.swing.JFrame {

    /**
     * Creates new form AdminScreen111111
     */
    public AdminScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminBackground = new javax.swing.JPanel();
        attendence = new javax.swing.JLabel();
        deleteUser = new javax.swing.JLabel();
        addUser1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Administrator Screen");

        AdminBackground.setBackground(new java.awt.Color(204, 255, 255));

        attendence.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        attendence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attendence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before attendant-list.png"))); // NOI18N
        attendence.setText("Attendence");
        attendence.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                attendenceMouseMoved(evt);
            }
        });
        attendence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendenceMouseExited(evt);
            }
        });

        deleteUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before delete user.png"))); // NOI18N
        deleteUser.setText("Delete User");
        deleteUser.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                deleteUserMouseMoved(evt);
            }
        });
        deleteUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteUserMouseExited(evt);
            }
        });

        addUser1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addUser1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before add user.png"))); // NOI18N
        addUser1.setText("Add User");
        addUser1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addUser1MouseMoved(evt);
            }
        });
        addUser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addUser1MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/pharma-A(logo).png"))); // NOI18N
        jLabel1.setText("Welcome to Admininistrator Screen:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please choose your Option");

        javax.swing.GroupLayout AdminBackgroundLayout = new javax.swing.GroupLayout(AdminBackground);
        AdminBackground.setLayout(AdminBackgroundLayout);
        AdminBackgroundLayout.setHorizontalGroup(
            AdminBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminBackgroundLayout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(deleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(addUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(attendence, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(AdminBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AdminBackgroundLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminBackgroundLayout.setVerticalGroup(
            AdminBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdminBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attendence, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(248, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attendenceMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendenceMouseMoved
        attendence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/after attendant-list.png")));
    }//GEN-LAST:event_attendenceMouseMoved

    private void attendenceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendenceMouseExited
        attendence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before attendant-list.png")));
    }//GEN-LAST:event_attendenceMouseExited

    private void deleteUserMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserMouseMoved

        deleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/after delete user.png"))); // NOI18N
    }//GEN-LAST:event_deleteUserMouseMoved

    private void deleteUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteUserMouseExited
        deleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before delete user.png"))); // NOI18N
    }//GEN-LAST:event_deleteUserMouseExited

    private void addUser1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUser1MouseMoved
        addUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/after add user.png"))); // NOI18N
    }//GEN-LAST:event_addUser1MouseMoved

    private void addUser1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUser1MouseExited
        addUser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before add user.png"))); // NOI18N
    }//GEN-LAST:event_addUser1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel AdminBackground;
    private javax.swing.JLabel addUser1;
    private javax.swing.JLabel attendence;
    private javax.swing.JLabel deleteUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
