/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjectFiles;

/**
 *
 * @author sajid
 */
public class UserScreen extends javax.swing.JFrame {

    /**
     * Creates new form UserScreen
     */
    public UserScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserScreenBackground = new javax.swing.JPanel();
        SalesLbl = new javax.swing.JLabel();
        ReceiptLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserScreenBackground.setBackground(new java.awt.Color(204, 255, 255));

        SalesLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SalesLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before shopping-bag.png"))); // NOI18N
        SalesLbl.setText("Booking");
        SalesLbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                SalesLblMouseMoved(evt);
            }
        });
        SalesLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalesLblMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalesLblMouseExited(evt);
            }
        });

        ReceiptLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ReceiptLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before bill.png"))); // NOI18N
        ReceiptLbl.setText("WaitingList");
        ReceiptLbl.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ReceiptLblMouseMoved(evt);
            }
        });
        ReceiptLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReceiptLblMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReceiptLblMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/pharma-A(logo).png"))); // NOI18N
        jLabel1.setText("       Welcome to INTI Hotel");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please choose your Option");

        javax.swing.GroupLayout UserScreenBackgroundLayout = new javax.swing.GroupLayout(UserScreenBackground);
        UserScreenBackground.setLayout(UserScreenBackgroundLayout);
        UserScreenBackgroundLayout.setHorizontalGroup(
            UserScreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserScreenBackgroundLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
            .addGroup(UserScreenBackgroundLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(UserScreenBackgroundLayout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(SalesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(ReceiptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UserScreenBackgroundLayout.setVerticalGroup(
            UserScreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserScreenBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(UserScreenBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReceiptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserScreenBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserScreenBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalesLblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesLblMouseMoved
        // TODO add your handling code here:
        SalesLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/after shopping-bag.png")));
    }//GEN-LAST:event_SalesLblMouseMoved

    private void SalesLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesLblMouseExited
        // TODO add your handling code here:
        SalesLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before shopping-bag.png")));
    }//GEN-LAST:event_SalesLblMouseExited

    private void ReceiptLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReceiptLblMouseExited
        // TODO add your handling code here:
        ReceiptLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/before bill.png")));
    }//GEN-LAST:event_ReceiptLblMouseExited

    private void ReceiptLblMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReceiptLblMouseMoved
        // TODO add your handling code here:
        ReceiptLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/after bill.png")));
    }//GEN-LAST:event_ReceiptLblMouseMoved

    private void SalesLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesLblMouseClicked
     Sales open=new Sales();
     open.setVisible(true);
    }//GEN-LAST:event_SalesLblMouseClicked

    private void ReceiptLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReceiptLblMouseClicked
Reciepts open=new Reciepts();
open.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_ReceiptLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ReceiptLbl;
    private javax.swing.JLabel SalesLbl;
    private javax.swing.JPanel UserScreenBackground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
